[versions]
jackson-databind = "2.20.1"
jackson-dataformat-yaml = "2.20.1"
jackson-datatype-jdk8 = "2.20.1"
jackson-datatype-jsr310 = "2.20.1"
jackson-module-parameter = "2.20.1"
javalin = "6.7.0"
jetty-client = "11.0.26"
junit-bom = "5.14.1"
jaxws = "2.3.1"
leshan = "1.5.0"
logback = "1.5.23"
lombok = "1.18.42"
mockito = "3.12.4"
slf4j = "2.0.17"
spotless = "8.1.0"
problem4j-core = "1.3.0"
problem4j-jackson = "1.3.0"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# BOMs
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }

# direct versions
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson-dataformat-yaml" }
jackson-module-parameter-names = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names", version.ref = "jackson-module-parameter" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-datatype-jdk8" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr310" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jetty-client = { module = "org.eclipse.jetty:jetty-client", version.ref = "jetty-client" }
jaxws-api = { module = "javax.xml.ws:jaxws-api", version.ref = "jaxws" }
leshan-client-cf = { module = "org.eclipse.leshan:leshan-client-cf", version.ref = "leshan" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
problem4j-core = { module = "io.github.problem4j:problem4j-core", version.ref = "problem4j-core" }
problem4j-jackson2 = { module = "io.github.problem4j:problem4j-jackson2", version.ref = "problem4j-jackson" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
